-- Real-portfolio seed for atlas.projects (V7 T131 — placeholders purged).
-- Idempotent: ON CONFLICT (project_key, version) DO NOTHING.
-- Rows marked [MELISSA-RECONCILE] carry draft economics pending the
-- Atlas-vs-Excel reconciliation; identity fields are real.
-- Placeholder rows ("Project N") are BANNED here — enforced by
-- tests/seed-hygiene.test.ts.

-- 6 Great Circle — Shelter Island · sales (broker launch late June; target ~$4.85M). [MELISSA-RECONCILE]
INSERT INTO atlas.projects (project_key, name, address, google_maps_url, entity_spv, market_id, asset_type, status, stage, purchase_date, sourcing_months, permitting_preconstruction_months, construction_months, sales_months, villa_sqft_ag, villa_sqft_bg, land_cost_cents, build_cost_per_sqft_cents, soft_costs_lump_sum_cents, soft_costs_breakdown, lender_name, senior_ltv_bps, interest_rate_bps, contingency_bps, origination_fee_bps, exit_fee_bps, interest_reserve_cents, loan_servicing_fee_cents, closing_costs_cents, other_fees, sale_price_override_cents, sale_price_per_sqft_override_cents, target_margin_bps, listing_date, under_contract_date, closing_date, listing_price_cents, actual_sale_price_cents, build_cost_curve) VALUES ('p1', '6 Great Circle', '6 Great Circle Drive, Shelter Island, NY 11964', NULL, 'Juno SPV 1 LLC', 'shelter_island', 'spec_home', 'committed', 'sales', '2025-06', 0, 4, 10, 3, 4000, 1000, 135000000, 48500, 0, NULL, NULL, 7500, 1000, NULL, 100, 50, 0, 0, 0, NULL, 485000000, NULL, NULL, '2026-06-25', NULL, NULL, NULL, NULL, NULL) ON CONFLICT (project_key, version) DO NOTHING;

-- 84 Sunset Beach Road — North Haven / Sag Harbor · pre-construction. Sqft = confirmed 5,317 AG + 2,479 BG (V6.1.5-017).
INSERT INTO atlas.projects (project_key, name, address, google_maps_url, entity_spv, market_id, asset_type, status, stage, purchase_date, sourcing_months, permitting_preconstruction_months, construction_months, sales_months, villa_sqft_ag, villa_sqft_bg, land_cost_cents, build_cost_per_sqft_cents, soft_costs_lump_sum_cents, soft_costs_breakdown, lender_name, senior_ltv_bps, interest_rate_bps, contingency_bps, origination_fee_bps, exit_fee_bps, interest_reserve_cents, loan_servicing_fee_cents, closing_costs_cents, other_fees, sale_price_override_cents, sale_price_per_sqft_override_cents, target_margin_bps, listing_date, under_contract_date, closing_date, listing_price_cents, actual_sale_price_cents, build_cost_curve) VALUES ('p2', '84 Sunset Beach Road', '84 Sunset Beach Road, Sag Harbor, NY 11963', NULL, 'Juno SPV 2 LLC', 'sag_harbor', 'spec_home', 'committed', 'pre_construction', '2026-03', 0, 3, 9, 1, 5317, 2479, 220000000, 43700, 0, NULL, 'Harrison Capital (USCNYC)', 7500, 1000, NULL, 100, 50, 32091800, 900000, 22700000, NULL, 800989300, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (project_key, version) DO NOTHING;

-- 540 Hands Creek — East Hampton · permitting (9+ month permit risk). [MELISSA-RECONCILE]
INSERT INTO atlas.projects (project_key, name, address, google_maps_url, entity_spv, market_id, asset_type, status, stage, purchase_date, sourcing_months, permitting_preconstruction_months, construction_months, sales_months, villa_sqft_ag, villa_sqft_bg, land_cost_cents, build_cost_per_sqft_cents, soft_costs_lump_sum_cents, soft_costs_breakdown, lender_name, senior_ltv_bps, interest_rate_bps, contingency_bps, origination_fee_bps, exit_fee_bps, interest_reserve_cents, loan_servicing_fee_cents, closing_costs_cents, other_fees, sale_price_override_cents, sale_price_per_sqft_override_cents, target_margin_bps, listing_date, under_contract_date, closing_date, listing_price_cents, actual_sale_price_cents, build_cost_curve) VALUES ('p4', '540 Hands Creek', '540 Hands Creek Road, East Hampton, NY 11937', NULL, 'Juno SPV 4 LLC', 'east_hampton', 'spec_home', 'committed', 'permitting', '2026-12', 0, 9, 9, 1, 6200, 1300, 175000000, 47000, 0, NULL, NULL, 7500, 1000, NULL, 100, 50, 0, 0, 0, NULL, 738779000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (project_key, version) DO NOTHING;

-- North Haven — Sag Harbor · permitting. [MELISSA-RECONCILE]
INSERT INTO atlas.projects (project_key, name, address, google_maps_url, entity_spv, market_id, asset_type, status, stage, purchase_date, sourcing_months, permitting_preconstruction_months, construction_months, sales_months, villa_sqft_ag, villa_sqft_bg, land_cost_cents, build_cost_per_sqft_cents, soft_costs_lump_sum_cents, soft_costs_breakdown, lender_name, senior_ltv_bps, interest_rate_bps, contingency_bps, origination_fee_bps, exit_fee_bps, interest_reserve_cents, loan_servicing_fee_cents, closing_costs_cents, other_fees, sale_price_override_cents, sale_price_per_sqft_override_cents, target_margin_bps, listing_date, under_contract_date, closing_date, listing_price_cents, actual_sale_price_cents, build_cost_curve) VALUES ('p12', 'North Haven', 'North Haven, Sag Harbor, NY 11963 (parcel)', NULL, 'Juno SPV 5 LLC', 'sag_harbor', 'spec_home', 'committed', 'permitting', '2026-05', 0, 9, 10, 2, 5000, 1500, 210000000, 43700, 0, NULL, NULL, 7500, 1000, NULL, 100, 50, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (project_key, version) DO NOTHING;
